[project]
name = "interaction-finder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "TEC", email = "git@tecosaur.net" }]
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "chonkie[semantic]>=1.1.2",
    "crawl4ai[pdf]>=0.7.4",
    "httpx>=0.28.1",
    "logfire>=0.4",
    "playwright-stealth>=2.0.0",
    "pydantic>=2.11.7",
    "pydantic-ai==1",
    "rich>=14.1.0",
    "scikit-learn>=1.7.1",
    "tomli>=2.2.1",
    "tomli-w>=1.1.0",
    "typer>=0.16.1",
]

[project.scripts]
interaction-finder = "interaction_finder.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.logfire]
ignore_no_config = true

[tool.hatch.build.targets.wheel]
packages = ["src/interaction_finder"]

[dependency-groups]
dev = [
    "pytest-cov>=6.2.1",
    "pytest-asyncio>=0.24.0",
    "dirty-equals>=0.9.0",
]
