[project]
name = "interaction-finder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "TEC", email = "git@tecosaur.net" }]
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "chonkie[semantic]>=1.1.2",
    "crawl4ai[pdf]>=0.7.4",
    "playwright-stealth>=2.0.0",
    "pydantic>=2.11.7",
    "rich>=14.1.0",
    "tomli>=2.2.1",
    "typer>=0.16.1",
]

[project.scripts]
interaction-finder = "interaction_finder.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["pytest-cov>=6.2.1"]
