"""HTML template for report generation.

Provides a Jinja2 template for rendering self-contained HTML reports
with embedded data, CSS, and JavaScript.
"""

import json
from typing import Any

from interaction_finder.report.assets import get_css, get_js

# HTML template with Jinja2 placeholders
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>

    <!-- Pico CSS from CDN -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.colors.min.css">

    <!-- Custom CSS -->
    <style>
{{ css }}
    </style>
</head>
<body>
    <!-- Header -->
    <header>
        <div class="header-content">
            <div class="header-info">
                <h1 class="header-title">{{ title }}</h1>
                <div class="header-stats">
                    <span class="stat-item">
                        <span class="stat-label">Topic:</span>
                        <span>{{ metadata.topic }}</span>
                    </span>
                    <span class="stat-item">
                        <span class="stat-label">Pairs:</span>
                        <span>{{ metadata.total_pairs }}</span>
                    </span>
                    {% for kind, count in metadata.entity_stats.items() %}
                    <span class="stat-item">
                        <span class="stat-label">{{ kind }}:</span>
                        <span>{{ count }}</span>
                    </span>
                    {% endfor %}
                    <span class="stat-item">
                        <span class="stat-label">Documents:</span>
                        <span>{{ metadata.resource_count }}</span>
                    </span>
                </div>
            </div>
            <div class="header-controls-wrapper">
                <div class="header-controls">
                    <div class="header-search">
                        <input type="search"
                               id="search-input"
                               placeholder="Search entities or relationships..."
                               aria-label="Search">
                    </div>
                    <label>
                        <input type="checkbox" id="show-rejected" role="switch">
                        Show rejected
                    </label>
                </div>
            </div>
        </div>
    </header>

    <!-- Left Sidebar: Pair List -->
    <aside id="sidebar">
        <!-- Rendered by JavaScript -->
    </aside>

    <!-- Main Content: Document Accordions -->
    <main id="content">
        <div class="content-placeholder">Select a pair to view documents</div>
    </main>

    <!-- Right Sidebar: Reasoning -->
    <aside id="rightbar">
        <div class="reasoning-panel">
            <p>Select a pair to view reasoning</p>
        </div>
    </aside>

    <!-- Footer -->
    <footer>
        <p>Generated by interaction-finder | {{ metadata.total_pairs }} pairs from {{ metadata.resource_count }} documents</p>
    </footer>

    <!-- Document Templates (pre-rendered HTML) -->
    <div id="document-templates" style="display: none;">
{{ document_templates }}
    </div>

    <!-- Embedded Data -->
    <script>
        window.REPORT_DATA = {{ data_json }};
    </script>

    <!-- JavaScript -->
    <script>
{{ js }}
    </script>
</body>
</html>
"""


def render_template(
    data: dict[str, Any],
    document_html: dict[str, str],
    title: str = "Extraction Report",
) -> str:
    """Render HTML report from prepared data.

    Args:
        data: Prepared report data from prepare_report_data() (JSON-serializable)
        document_html: Mapping of doc_id -> pre-rendered HTML string
        title: Report title

    Returns:
        Complete HTML document as string
    """
    # Simple template rendering without Jinja2 dependency
    # Use string replacement for placeholders
    html = HTML_TEMPLATE

    # Build document templates HTML
    doc_templates_parts = []
    for doc_id, doc_html in document_html.items():
        # Wrap each document's HTML in a <template> tag with unique ID
        doc_templates_parts.append(
            f'        <template id="doc-template-{_escape_html(doc_id)}">\n'
            f'            <div class="document-text">{doc_html}</div>\n'
            f"        </template>"
        )
    document_templates_html = "\n".join(doc_templates_parts)

    # Replace placeholders
    replacements = {
        "{{ title }}": _escape_html(title),
        "{{ metadata.topic }}": _escape_html(data["metadata"]["topic"]),
        "{{ metadata.total_pairs }}": str(data["metadata"]["total_pairs"]),
        "{{ metadata.resource_count }}": str(data["metadata"]["resource_count"]),
        "{{ css }}": get_css(),
        "{{ js }}": get_js(),
        "{{ data_json }}": json.dumps(data, ensure_ascii=False, indent=2),
        "{{ document_templates }}": document_templates_html,
    }

    for placeholder, value in replacements.items():
        html = html.replace(placeholder, value)

    # Handle entity stats loop
    entity_stats_html = ""
    for kind, count in data["metadata"]["entity_stats"].items():
        entity_stats_html += f"""
                <span class="stat-item">
                    <span class="stat-label">{_escape_html(kind)}:</span>
                    <span>{count}</span>
                </span>"""

    # Replace the Jinja2 loop with rendered HTML
    loop_start = "{% for kind, count in metadata.entity_stats.items() %}"
    loop_end = "{% endfor %}"
    start_idx = html.find(loop_start)
    end_idx = html.find(loop_end)

    if start_idx != -1 and end_idx != -1:
        # Find the content between loop tags (the template)
        html = html[:start_idx] + entity_stats_html + html[end_idx + len(loop_end) :]

    return html


def _escape_html(text: str) -> str:
    """Escape HTML special characters.

    Args:
        text: Text to escape

    Returns:
        HTML-safe text
    """
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )
