"""Pydantic output models for keyword research pipeline stages."""

from typing import Literal

from pydantic import BaseModel, Field

from interaction_finder.keywords.extractors import ScoredKeyword
from interaction_finder.resources import ResourcePool


class QueryExpansionOut(BaseModel):
    """Expanded queries tailored for finding review articles and bridging terms.

    Generated by query_expander_agent to target review/summary articles
    that discuss the topic comprehensively.
    """

    queries: list[str] = Field(
        min_length=1,
        max_length=5,
        description="Search queries designed to find review articles",
    )
    reasoning: str = Field(
        min_length=20,
        description="Why these queries target review articles and bridging terms",
    )


class ResultSelectionOut(BaseModel):
    """LLM decision on which search results to fetch and process.

    Generated by result_selector_agent after reviewing search result
    titles and snippets.
    """

    selected_indices: list[int] = Field(
        description="Zero-based indices of results to fetch (in order of priority)"
    )
    reasoning: str = Field(
        min_length=20, description="Why these results were selected as likely reviews"
    )


class ExtractedKeywordsOut(BaseModel):
    """Keywords extracted by all methods (RAKE, YAKE, TF-IDF, KeyBERT).

    Contains raw output from each extraction method before LLM evaluation.
    """

    keywords_by_method: dict[str, list[ScoredKeyword]] = Field(
        description="Keywords grouped by extraction method name"
    )
    total_unique: int = Field(ge=0, description="Total unique keywords across methods")


class KeywordEvaluationOut(BaseModel):
    """LLM evaluation of which keywords are useful as bridging terms.

    Generated by keyword_evaluator_agent for a single document.
    Identifies keywords that could help find related literature.
    """

    bridging_terms: list[str] = Field(
        description="Keywords identified as useful bridging terms for literature search"
    )
    reasoning: str = Field(
        min_length=20,
        description="Why these keywords are good bridging terms vs noise",
    )


class DocumentSummaryOut(BaseModel):
    """Summary of a single document's content and relevance to the topic.

    Generated by keyword_evaluator_agent alongside KeywordEvaluationOut.
    Provides context for reflection stage.
    """

    summary: str = Field(
        min_length=50, max_length=750, description="Concise summary of document content"
    )
    related_areas: list[str] = Field(
        description="Research areas related to topic worth investigating further"
    )
    bridging_terms: list[str] = Field(
        description="Bridging terms identified from this document"
    )
    coverage_contribution: str = Field(
        min_length=20,
        description="What new coverage this document adds (or doesn't add)",
    )


class ReflectionOut(BaseModel):
    """Decision on whether to continue searching or stop.

    Generated by reflector_agent after reviewing all document summaries.
    Assesses whether sufficient coverage has been achieved.
    """

    decision: Literal["continue", "stop"] = Field(
        description="Whether to continue with more searches or stop"
    )
    reasoning: str = Field(
        min_length=30,
        description="Why coverage is sufficient (stop) or gaps remain (continue)",
    )
    new_search_angles: list[str] = Field(
        default_factory=list,
        description="New search angles to explore if continuing (empty if stopping)",
    )


class BridgingTermsOut(BaseModel):
    """Final output: deduplicated list of bridging terms discovered.

    Returned at the end of the keyword research pipeline.
    """

    terms: list[str] = Field(
        description="Unique bridging terms discovered, sorted alphabetically"
    )
    total_documents_processed: int = Field(
        ge=0, description="Total number of documents analyzed"
    )
    rounds_completed: int = Field(ge=1, description="Number of search rounds completed")
    coverage_assessment: str = Field(
        min_length=50,
        description="Final assessment of coverage and what was discovered",
    )
    resources: ResourcePool = Field(
        description="Complete document pool with all processed content and provenance"
    )
